%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventDomainAdmin
%% Source: /net/isildur/ldisk/daily_build/r14b04_prebuild_opu_o.2011-10-03_20/otp_src_R14B04/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTDOMAINADMIN_HRL).
-define(OE_COSEVENTDOMAINADMIN_HRL, true).




-endif.


