%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_SequenceProxyPullConsumer
%% Source: /net/isildur/ldisk/daily_build/r14b04_prebuild_opu_o.2011-10-03_20/otp_src_R14B04/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_SEQUENCEPROXYPULLCONSUMER_HRL).
-define(COSNOTIFYCHANNELADMIN_SEQUENCEPROXYPULLCONSUMER_HRL, true).




-endif.


