%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_VirtualFileSystem
%% Source: /net/isildur/ldisk/daily_build/r14b04_prebuild_opu_o.2011-10-03_20/otp_src_R14B04/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_VIRTUALFILESYSTEM_HRL).
-define(COSFILETRANSFER_VIRTUALFILESYSTEM_HRL, true).




-endif.


