%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime_UTO
%% Source: /net/isildur/ldisk/daily_build/r14b04_prebuild_opu_o.2011-10-03_20/otp_src_R14B04/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_UTO_HRL).
-define(COSTIME_UTO_HRL, true).




-endif.


