%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_Resource
%% Source: /net/isildur/ldisk/daily_build/r14b04_prebuild_opu_o.2011-10-03_20/otp_src_R14B04/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_RESOURCE_HRL).
-define(COSTRANSACTIONS_RESOURCE_HRL, true).




-endif.


