%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosPropertyService_UnsupportedProperty
%% Source: /net/isildur/ldisk/daily_build/r14b04_prebuild_opu_o.2011-10-03_20/otp_src_R14B04/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosPropertyService_UnsupportedProperty').
-ic_compiled("4_2_27").


-include("CosPropertyService.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosPropertyService/UnsupportedProperty:1.0",
                   "UnsupportedProperty",[]}.

%% returns id
id() -> "IDL:omg.org/CosPropertyService/UnsupportedProperty:1.0".

%% returns name
name() -> "CosPropertyService_UnsupportedProperty".



