%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_SynchronizationUnavailable
%% Source: /net/isildur/ldisk/daily_build/r14b04_prebuild_opu_o.2011-10-03_20/otp_src_R14B04/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_SynchronizationUnavailable').
-ic_compiled("4_2_27").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/SynchronizationUnavailable:1.0",
                   "SynchronizationUnavailable",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/SynchronizationUnavailable:1.0".

%% returns name
name() -> "CosTransactions_SynchronizationUnavailable".



