%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PushConsumer
%% Source: /net/isildur/ldisk/daily_build/r14b04_prebuild_opu_o.2011-10-03_20/otp_src_R14B04/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PUSHCONSUMER_HRL).
-define(COSEVENTCOMM_PUSHCONSUMER_HRL, true).




-endif.


