%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventComm_PusherS
%% Source: /net/isildur/ldisk/daily_build/r14b04_prebuild_opu_o.2011-10-03_20/otp_src_R14B04/lib/cosEvent/src/cosEventApp.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCOMM_PUSHERS_HRL).
-define(OE_COSEVENTCOMM_PUSHERS_HRL, true).




-endif.


